version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=carrot
    ports:
      - "5672:5672"


  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_PASS=rdis
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=carrot
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - redis
      - rabbitmq

  client:
    build: ./client
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    build: ./elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

  logstash:
    build: ./logstash
    container_name: logstash
    environment:
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=carrot
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - rabbitmq
      - elasticsearch
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch