version: "3"

services:
  client:
    build: ./client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"

  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    
